### ISSUE TITLE
Further code upgrade

### ISSUE THREAD

**Issue by ghost** [spiemonte/LeonardYM#2]
Such a question for you, @spiemonte. Will your code be updated in the future or is this already the final version of the code? Is it possible to add Yukawa interactions in the future? Your code is pretty well organized, and it doesn't seem like a difficult task to me. What parts of the code mostly need modification? What ideas do you have on this?

**Comment by spiemonte** [comment]
The code is in a stable version, not necessarely final. I am planning in some future to add Yukawa interactions, in particular to allow simulations of N=2 SYM. 

To include Yukawa interactions there are two aspects we need to consider:
* The target theory, as the structure of Yukawa interactions is different in N=2 SYM, in SQCD or in simpler pure Higgs-Yukawa theories.
* The fermion discretization, as overlap fermions with exact chiral symmetry require a special care when defining the chiral projectors.

Which theory/formulation would be more interesting for you? 

The implementation would require first to define a new "extended" DiracOperator, i.e. the operator defining the quadratic part of the fermion action including the Yukawa couplings. Then, we would need to think how to update the scalar fields when Yukawa interactions are present (at the moment the scalar fields are updated separately at the end of the HMC trajectory, so that it is possible to simulate easily gauge+fermion+scalar, but with scalar-fermion interations we would need to think to an alternative solution/extension).

**Comment by ghost** [comment]
@spiemonte, Personally, I would be very interested in simulating SU(5) GUT breaking to SM on the lattice and, if possible, with dynamical fermions in an anti-fundamental representation in the one flavor case, so conjugated SU(3) triplet times SU(2) doublet. 

How difficult is it? As far as I know, your code allows you to simulate two scalar fields at the same time in fundamental and adjoint reps that only interact with the gauge field and not with each other, so we need a cross potential of 5 and 24.  Also, the adjoint scalar is now complex but easy to set to real numbers, just edit the matrix def, remove conj and real in some places of scalar action, scalar updater, and scalar measurements. 
The quartic terms are present in the action of scalar fields, but this gives a very low v.e.v when simulating, changing -lambda/24 and -m-8 terms with common -lambda/4 and -m, helps to rise v.e.v but immediately there is a need for large steps of integration for stability.

Fermion reps are flexible too, and setting them anti-fundamental in the fermion force by conjugating the generators of SU(5) is not a problem. Of course, we need yukawa interaction between higgs conjugated rep 5-multiplet( conjugated SU(3) times conjugated SU(2) ) and fermion antifundamental 5, plus yukawa matrices for mass split. 

Well, tell me, are there any obstacles? I've already dug a little deeper into your code, but you still know it better, just hint what I might have missed, I really want to hear your thoughts on this.

**Comment by spiemonte** [comment]
I would split the development in four parts:

* First a proper definition of the SU(5) links in the <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/utils/ConvertLattice.cpp#L13>antifundamental representation</a> and of the <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/utils/LieGenerators.h#L71>generators</a> for the Dirac operator is needed, including the exponential map (should be relatively simple).
* The changes for the fermion HMC should be minimal (for instance <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/hmc_forces/FermionForce.cpp#L33>here</a>). There could be some part here and there where the representation is hard coded, but it should be relatively simple to fix.
* The scalar action can be changed, are we sure about the symmetric covariant derivative? If I remember correctly, <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/actions/AdjointScalarAction.cpp#L15>I implemented it</a> thinking about an "improved" scalar action, before realising that such an action would have doublers (I must check again).
* The Yukawa interactions seem more complex to implement.  At the moment, as I said above, the scalars are <a href=https://github.com/spiemonte/LeonardYM/blob/master/source/scalar_updaters/AdjointMetropolisScalarUpdater.cpp#L105>updated locally</a> by simple metropolis at the end of the HCM trajectory. I implemented scalars in this way because I am convinced that it should be faster, including them in the HCM is not complicated. The HMC would be indeed required for Yukawa interactions.

I think one should proceed step by step, starting from the top to bottom.

**Comment by ghost** [comment]
@spiemonte, yes i messed up a little, there's no need for symmetric derivative.
The adjoint scalar field must transform as Φ→UΦU†, similar to gauge fields V[mu][nu]→UV[mu][nu]U†.
While the fundamental scalar transforms as φ→Uφ.
The covariant derivative for adjoint scalar in continuum is D[mu]Φ=partial_derivative[mu]Φ + ig(ΦU[mu] - U[mu]Φ). 

One thing that worries me is that usually the adjoint scalar in su(5) gut is constructed in matrix form, like the gauge fields. 
Sum over generators of SU(5) Σ[a=1][24] Φ[a] λ[a].

UPD!:
If i understood correctly, you implemented a convert routine which converts fundamental gauge links to adjoint representation, and the covariant derivative in adjoint scalar action depends on AdjointGroup matrix(which itself is converted from fundamental). So we don't need this additional U[x][mu]† term in covariant derivative?

Is adjoint scalar in your code equivalent to the matrix representation of the adjoint scalar?

P.S 
Do you have some sort of messenger? So we could communicate more frequently about the development.

**Comment by spiemonte** [comment]
Yes, exactly, now I understand your point. In the code, adjoint scalar (or fermion) fields are written as vectors with N^2 - 1 components, and the covariant derivative acting accordingly as a (N^2-1)x(N^2-1) matrix. You could also write the same field as a traceless antisymmetric matrix, and you would end up to the same action (however the code for the adjoint and the fundamental rep for fermions would be radically different).

The only point I do not understand now is why I have written the adjoint scalar fields as complex fields. I cannot recall the reason, but I am conviced, as you say, that the adjoint scalar field should be real by definition.

I have just included a small bugfix, now you can compile the code in the fundamental representation of SU(5) (nc=5 adjoint=false). We can organize a meeting to discuss the plan for further developments these days, I have a tight schedule, but I should be available on the late afternoon.

**Comment by ghost** [comment]
@spiemonte, I sent you an email about our project, so please reply there, I think there is no need to breed a long discussion here in the comments.

**Comment by daschaich** [comment]
Quick comment and question:

Using NxN matrices for adjoint fields saves a lot of flops compared to (N^2-1)-component vectors, especially as N gets larger.  For N=7 we got a roughly 15x speedup in [SUSY LATTICE](https://github.com/daschaich/susy) upon implementing that change in 2016.

Does SU(5) GUT breaking to SM involve only vector-like theories?  I'd advise caution with chiral lattice gauge theories.

**Comment by ghost** [comment]
@daschaich  We have already excluded fermion sector from a future project due to the huge computational cost, so it doesn't matter. We restrict ourselves to simulating the gauge-boson sector of SU(5) GUT.
