### ISSUE TITLE
Scalar field gauge fixing

### ISSUE THREAD

**Issue by ghost** [spiemonte/LeonardYM#6]
Hi @spiemonte.
I explore gauge-fixed propagators of gauge bosons of SU(5) theory, i have implemented unitary gauge in scalar action to explicitly break the gauge symmetry ( Φ' = |Φ|λ_24,  |Φ| is higgs length and λ_24 is Hypercharge generator of SU(5)   ), and suitable propagators. But no matter what they remain massless(for any beta or mass of higgs). 
and higgs of the fundamental representation in unitary gauge, on the contrary, works as it should. 
Increasing the number of adjoint scalar fields (flavors) doesn't help either.
Are you sure that the scalar action implemented correctly?

**Comment by spiemonte** [comment]
If you have changed the scalar action, you should check your implementation to see whether the scalar action works as you would expect. 

Let me just comment here that I do not think it is a good idea to break the gauge symmetry directly in the scalar action, otherwise the results you will get will be most likely meaningless no matter how you are going to compute them (expectation values will acquire gauge non-invariant contributions difficult to disentangle from the gauge invariant physical ones). You will also need to include gauge fixing terms for the gauge bosons and relative ghost in the simulations, which would be expensive. If you want to run a simulation in the Higgs phase, just tune and use the quartic and quadratic couplings appropriately.

**Comment by ghost** [comment]
I also tried to set a constant vector over all spacetime in RandomScalarUpdater, without updating the scalar fields at all, this is failed to produce correct result. I was inspecting the scalar force which contributes to conjugate momenta, and it seems it works good. But don't quite understand why fundamental higgs gives masses to propagators but adjoint higgs is not.
Okay, So you advise me to use gauge invariant operators of gauge bosons for correlation functions?
